spring:
  datasource:
    username: college_student
    password: college_student
    url: jdbc:mysql://localhost:3306/college_student

  jpa:
    hibernate:
      ddl-auto: update
      # reminders for options
      # none
      # update
    show-sql: true

  sql:
    init:
      mode: always
      # reminders for options
      # always
      # never
      # embedded